language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/99ce9744dffc79901f02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
